//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heladeria.Data.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compra
    {
        public int IdCompra { get; set; }
        public int IdArticulo { get; set; }
        public int Cantidad { get; set; }
        public int IdDetalleCompra { get; set; }
        public Nullable<decimal> Total { get; set; }
    
        public virtual Articulo Articulo { get; set; }
        public virtual DetalleCompra DetalleCompra { get; set; }
    }
}
