//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heladeria.Data.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class InformeCaja
    {
        public Nullable<int> Local { get; set; }
        public Nullable<int> Aplicacion { get; set; }
        public Nullable<decimal> Efectivo { get; set; }
        public Nullable<decimal> OtroMedio { get; set; }
        public System.DateTime Fecha { get; set; }
        public int Id { get; set; }
    }
}
