//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heladeria.Data.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class InformeMasVendidos
    {
        public string Nombre { get; set; }
        public int Cantidad { get; set; }
        public int Id { get; set; }
        public System.DateTime Desde { get; set; }
        public Nullable<System.DateTime> Hasta { get; set; }
    }
}
