//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heladeria.Data.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedido
    {
        public int IdPedido { get; set; }
        public int IdUsuario { get; set; }
        public bool Leido { get; set; }
        public bool Entregado { get; set; }
        public int IdArticulo { get; set; }
        public int Cantidad { get; set; }
        public int IdTipoPago { get; set; }
        public string Destino { get; set; }
        public Nullable<int> IdAreaEnvio { get; set; }
        public Nullable<int> IdRepartidor { get; set; }
        public decimal Total { get; set; }
        public System.DateTime Fecha { get; set; }
    
        public virtual AreaEnvio AreaEnvio { get; set; }
        public virtual Articulo Articulo { get; set; }
        public virtual Repartidor Repartidor { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual TipoPago TipoPago { get; set; }
    }
}
