//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heladeria.Data.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venta
    {
        public int IdVenta { get; set; }
        public string Comentario { get; set; }
        public int IdCliente { get; set; }
        public System.DateTime Fecha { get; set; }
        public int IdTipoPago { get; set; }
        public decimal Total { get; set; }
        public int IdDetalle { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual DetalleVenta DetalleVenta { get; set; }
        public virtual TipoPago TipoPago { get; set; }
    }
}
