// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Heladeria.API.Data
{
    public partial class AreaEnvio
    {
        public AreaEnvio()
        {
            Pedido = new HashSet<Pedido>();
        }

        public int IdAreaEnvio { get; set; }
        public string Nombre { get; set; }
        public decimal Precio { get; set; }

        public virtual ICollection<Pedido> Pedido { get; set; }
    }
}