// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Heladeria.API.Data
{
    public partial class Articulo
    {
        public Articulo()
        {
            Compra = new HashSet<Compra>();
            DetalleVenta = new HashSet<DetalleVenta>();
            Pedido = new HashSet<Pedido>();
        }

        public int IdArticulo { get; set; }
        public string Codigo { get; set; }
        public string Nombre { get; set; }
        public int Idcategoria { get; set; }
        public decimal PrecioCompra { get; set; }
        public int Cantidad { get; set; }
        public int? Minimo { get; set; }
        public int? Maximo { get; set; }
        public int IdProveedor { get; set; }
        public decimal PrecioVenta { get; set; }
        public byte[] Imagen { get; set; }

        public virtual Proveedor IdProveedorNavigation { get; set; }
        public virtual Categoria IdcategoriaNavigation { get; set; }
        public virtual ICollection<Compra> Compra { get; set; }
        public virtual ICollection<DetalleVenta> DetalleVenta { get; set; }
        public virtual ICollection<Pedido> Pedido { get; set; }
    }
}