// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Heladeria.API.Data
{
    public partial class Cliente
    {
        public Cliente()
        {
            Venta = new HashSet<Venta>();
        }

        public int IdCliente { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public int IdCondicionFiscal { get; set; }
        public string Cuit { get; set; }

        public virtual CondicionFiscal IdCondicionFiscalNavigation { get; set; }
        public virtual ICollection<Venta> Venta { get; set; }
    }
}