// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Heladeria.API.Data
{
    public partial class Compra
    {
        public int IdCompra { get; set; }
        public int IdArticulo { get; set; }
        public int Cantidad { get; set; }
        public int IdDetalleCompra { get; set; }
        public decimal? Total { get; set; }

        public virtual Articulo IdArticuloNavigation { get; set; }
        public virtual DetalleCompra IdDetalleCompraNavigation { get; set; }
    }
}