// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Heladeria.API.Data
{
    public partial class DetalleCompra
    {
        public DetalleCompra()
        {
            Compra = new HashSet<Compra>();
        }

        public int IdDetalleCompra { get; set; }
        public int Lote { get; set; }
        public int IdProveedor { get; set; }
        public DateTime Fecha { get; set; }

        public virtual Proveedor IdProveedorNavigation { get; set; }
        public virtual ICollection<Compra> Compra { get; set; }
    }
}