// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Heladeria.API.Data
{
    public partial class DetalleVenta
    {
        public DetalleVenta()
        {
            Venta = new HashSet<Venta>();
        }

        public int IdDetalleVenta { get; set; }
        public int IdArticulo { get; set; }
        public int Cantidad { get; set; }
        public decimal PrecioUnitario { get; set; }

        public virtual Articulo IdArticuloNavigation { get; set; }
        public virtual ICollection<Venta> Venta { get; set; }
    }
}