// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Heladeria.API.Data
{
    public partial class InformeMasVendidos
    {
        public string Nombre { get; set; }
        public int Cantidad { get; set; }
        public DateTime Fecha { get; set; }
        public int Id { get; set; }
    }
}