// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Heladeria.API.Data
{
    public partial class Pedido
    {
        public int IdPedido { get; set; }
        public int IdUsuario { get; set; }
        public bool? Leido { get; set; }
        public bool? Entregado { get; set; }
        public int IdArticulo { get; set; }
        public int Cantidad { get; set; }
        public int IdTipoPago { get; set; }
        public string Destino { get; set; }
        public int? IdAreaEnvio { get; set; }
        public int? IdRepartidor { get; set; }
        public decimal? Total { get; set; }
        public DateTime? Fecha { get; set; }

        public virtual AreaEnvio IdAreaEnvioNavigation { get; set; }
        public virtual Articulo IdArticuloNavigation { get; set; }
        public virtual Repartidor IdRepartidorNavigation { get; set; }
        public virtual TipoPago IdTipoPagoNavigation { get; set; }
        public virtual Usuario IdUsuarioNavigation { get; set; }
    }
}