// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Heladeria.API.Data
{
    public partial class Proveedor
    {
        public Proveedor()
        {
            Articulo = new HashSet<Articulo>();
            DetalleCompra = new HashSet<DetalleCompra>();
        }

        public int IdProveedor { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public string Codigo { get; set; }
        public string Ciudad { get; set; }
        public string Pais { get; set; }
        public string Telefono { get; set; }
        public int IdCondicionFiscal { get; set; }
        public string Cuit { get; set; }

        public virtual CondicionFiscal IdCondicionFiscalNavigation { get; set; }
        public virtual ICollection<Articulo> Articulo { get; set; }
        public virtual ICollection<DetalleCompra> DetalleCompra { get; set; }
    }
}