// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Heladeria.API.Data
{
    public partial class Repartidor
    {
        public Repartidor()
        {
            Pedido = new HashSet<Pedido>();
        }

        public int IdRepartidor { get; set; }
        public string Dni { get; set; }
        public string Nombre { get; set; }
        public string Celular { get; set; }

        public virtual ICollection<Pedido> Pedido { get; set; }
    }
}