// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Heladeria.API.Data
{
    public partial class TipoPago
    {
        public TipoPago()
        {
            Pedido = new HashSet<Pedido>();
            Venta = new HashSet<Venta>();
        }

        public int IdTipoPago { get; set; }
        public string Nombre { get; set; }
        public string Codigo { get; set; }

        public virtual ICollection<Pedido> Pedido { get; set; }
        public virtual ICollection<Venta> Venta { get; set; }
    }
}