// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Heladeria.API.Data
{
    public partial class Venta
    {
        public int IdVenta { get; set; }
        public string Comentario { get; set; }
        public int IdCliente { get; set; }
        public DateTime Fecha { get; set; }
        public int IdTipoPago { get; set; }
        public decimal Total { get; set; }
        public int IdDetalle { get; set; }

        public virtual Cliente IdClienteNavigation { get; set; }
        public virtual DetalleVenta IdDetalleNavigation { get; set; }
        public virtual TipoPago IdTipoPagoNavigation { get; set; }
    }
}